version: 0.0
os: linux 
files:
  - source: /
    destination: /var/www/projects/ichs-be
file_exists_behavior: OVERWRITE
permissions:
  - object: /var/www/projects/ichs-be
    owner: web
    group: web
    mode: 755
hooks:
  AfterInstall:
    - location: deploy/after_install.sh     
      timeout: 300
      runas: web
